#--------------------------------------------------------------------
#	Home Assistant - Batteries
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-02-07
#	Description :	Set configuration to Batteries
#--------------------------------------------------------------------

homeassistant:
  customize:
    input_boolean.battery_notifications:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true

group:
  Batteries Status:
    name: Estado das Baterias
    control: hidden
    entities:
      - sensor.door_sensor
      - sensor.motion_sensor
      - sensor.illumination_sensor
      - sensor.temperature_sensor
      - sensor.humidity_sensor
      - input_boolean.battery_notifications

sensor:
  platform: template
  sensors:
    door_sensor:
      friendly_name: Bateria sensor porta principal
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.binary_sensor.door_window_sensor_158d0001bf26c9.attributes.battery_level %}
          {{ states.binary_sensor.door_window_sensor_158d0001bf26c9.attributes.battery_level|round }}
        {% else %}
          {{ states.sensor.door_sensor.state }}
        {%- endif %}
      icon_template: >
        {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

    motion_sensor:
      friendly_name: Bateria sensor movimento
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.binary_sensor.motion_sensor_158d0001e08eea.attributes.battery_level %}
          {{ states.binary_sensor.motion_sensor_158d0001e08eea.attributes.battery_level|round }}
        {% else %}
          {{ states.sensor.motion_sensor.state }}
        {%- endif %}
      icon_template: >
        {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

    illumination_sensor:
      friendly_name: Bateria sensor iluminação quarto
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.sensor.illumination_158d0001e08eea.attributes.battery_level %}
          {{ states.sensor.illumination_158d0001e08eea.attributes.battery_level|round }}
        {% else %}
          {{ states.sensor.illumination_sensor.state }}
        {%- endif %}
      icon_template: >
        {% set battery_level = states.sensor.illumination_sensor.state|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

    temperature_sensor:
      friendly_name: Bateria sensor temperatura
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.sensor.temperature_158d000201f774.attributes.battery_level %}
          {{ states.sensor.temperature_158d000201f774.attributes.battery_level|round }}
        {% else %}
          {{ states.sensor.temperature_sensor.state }}
        {%- endif %}
      icon_template: >
        {% set battery_level = states.sensor.temperature_sensor.state|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

    humidity_sensor:
      friendly_name: Bateria sensor humidade
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.sensor.humidity_158d000201f774.attributes.battery_level %}
          {{ states.sensor.humidity_158d000201f774.attributes.battery_level|round }}
        {% else %}
          {{ states.sensor.humidity_sensor.state }}
        {%- endif %}
      icon_template: >
        {% set battery_level = states.sensor.humidity_sensor.state|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

input_boolean:
  battery_notifications:
    name: Notificações da bateria
    initial: on
    icon: mdi:battery-charging-wireless

automation:
  - alias: Alerta Para Substituir a Bateria dos Sensores
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.door_sensor
        - sensor.motion_sensor
        - sensor.illumination_sensor
        - sensor.temperature_sensor
        - sensor.humidity_sensor
      below: 15
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.battery_notifications.state == "on" }}'
    action:
      - service: notify.my_pushbullet
        data_template:
          message: 'Alerta! {{ trigger.from_state.attributes.friendly_name }} necessita de ser substituída, apenas tem {{ trigger.from_state.state }}% de bateria restante!!'
