#--------------------------------------------------------------------
#	Home Assistant - Datetime
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-17
#	Description :	Set configuration to Datetime
#--------------------------------------------------------------------

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

group:
  Datetime:
    name: Data e Hora
    entities:
      - sensor.date
      - sensor.time
