#--------------------------------------------------------------------
#	Home Assistant - Devices
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-17
#	Description :	Set configuration to Devices
#--------------------------------------------------------------------

homeassistant:
  customize:
    sensor.flavio_phone:
      friendly_name: Flávio Pinho
      entity_picture: /local/images/flavio_pinho.jpg
    device_tracker.flavio_tracker:
      friendly_name: Flávio Pinho
      entity_picture: /local/images/flavio_pinho.jpg
    sensor.flaviopinhodt_eth:
      friendly_name: Desktop de Flávio Pinho
      icon: mdi:desktop-tower
    sensor.fpinho:
      friendly_name: Raspberry Secundário
      icon: mdi:server
    sensor.pipplware:
      friendly_name: PiPplware
      icon: mdi:server
    sensor.xp1000:
      friendly_name: Octagon SF8 HD
      icon: mdi:youtube-play
    sensor.smart_camera:
      friendly_name: Smart Camera
      icon: mdi:webcam
    sensor.vacuum:
      friendly_name: Xiaomi Vacuum
      icon: mdi:broom
    sensor.light_rgb:
      friendly_name: Luz Quarto RGB
      icon: mdi:lightbulb
    sensor.xiaomi_gateway:
      friendly_name: Xiaomi Gateway
      icon: mdi:google

group:
  Devices:
    name: Dispositivos
    entities:
      - sensor.flaviopinhodt_eth
      - sensor.pipplware
      - sensor.fpinho
      - sensor.xp1000
      - sensor.smart_camera
      - sensor.vacuum
      - sensor.light_rgb
      - sensor.xiaomi_gateway

sensor:
  platform: template
  sensors:
    flaviopinhodt_eth:
      value_template: '{% if is_state("device_tracker.flaviopinhodt_eth", "home") %} Ligado {% else %} Desligado {%- endif %}'
    pipplware:
      value_template: '{% if is_state("device_tracker.pipplware", "home") %} Ligado {% else %} Desligado {%- endif %}'
    fpinho:
      value_template: '{% if is_state("device_tracker.fpinho", "home") %} Ligado {% else %} Desligado {%- endif %}'
    xp1000:
      value_template: '{% if is_state("device_tracker.xp1000", "home") %} Ligado {% else %} Desligado {%- endif %}'
    smart_camera:
      value_template: '{% if is_state("device_tracker.smart_camera", "home") %} Ligado {% else %} Desligado {%- endif %}'
    vacuum:
      value_template: '{% if is_state("device_tracker.vacuum", "home") %} Ligado {% else %} Desligado {%- endif %}'
    light_rgb:
      value_template: '{% if is_state("device_tracker.light_rgb", "home") %} Ligado {% else %} Desligado {%- endif %}'
    xiaomi_gateway:
      value_template: '{% if is_state("device_tracker.xiaomi_gateway", "home") %} Ligado {% else %} Desligado {%- endif %}'
