#--------------------------------------------------------------------
#	Home Assistant - Doors
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-02-08
#	Description :	Set configuration to Doors
#--------------------------------------------------------------------

homeassistant:
  customize:
    sensor.door_main:
      friendly_name: Porta principal
      icon: mdi:door
    binary_sensor.door_window_sensor_158d0001bf26c9:
      friendly_name: Sensor porta principal

group:
  Door:
    name: Entrada
    entities:
      - sensor.door_main

sensor:
  platform: template
  sensors:
    door_main:
      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001bf26c9", "on") %} Aberta {% else %} Fechada {%- endif %}'

automation:
  - alias: Porta Principal Aberta
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001bf26c9
      from: 'off'
      to: 'on'
    action:
      - service: notify.my_pushbullet
        data:
          message: 'Porta principal aberta'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_mac
          ringtone_id: 10
          ringtone_vol: 30
