#--------------------------------------------------------------------
#	Home Assistant - Gateway
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-30
#	Description :	Set configuration to Gateway
#--------------------------------------------------------------------

homeassistant:
  customize:
    input_boolean.mute_gateway_sounds:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true
    script.play_sound:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true
    script.play_sound_loop:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true

xiaomi_aqara:
  discovery_retry: 10
  gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key
     host: !secret xiaomi_host

group:
  Xiaomi Gateway:
    name: Xiaomi Gateway
    control: hidden
    entities:
      - input_boolean.mute_gateway_sounds
      - input_select.gateway_sound
      - input_number.gateway_volume
      - input_number.loop_delay
      - script.play_sound
      - script.play_sound_loop
      - script.play_sound_single

input_boolean:
  mute_gateway_sounds:
    name: Silenciar
    icon: mdi:volume-off

script:
  play_sound:
    alias: "Reproduzir som em ciclo"
    sequence:
      - condition: state
        entity_id: input_boolean.mute_gateway_sounds
        state: 'off'
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_mac
          ringtone_id: "{{ states.input_select.gateway_sound.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"
      - delay: '00:00:{{ states.input_number.loop_delay.state | int }}'
      - service: script.play_sound_loop

  play_sound_loop:
    alias: "Reproduzir som selecionado em ciclo"
    sequence:
      - condition: state
        entity_id: input_boolean.mute_gateway_sounds
        state: 'off'
      - delay: '00:00:{{ states.input_number.loop_delay.state | int }}'
      - service: script.play_sound

  play_sound_single:
    alias: "Reproduzir som"
    sequence:
      - condition: state
        entity_id: input_boolean.mute_gateway_sounds
        state: 'off'
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_mac
          ringtone_id: "{{ states.input_select.gateway_sound.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"

input_number:
  gateway_volume:
    name: Volume
    initial: 10
    min: 0
    max: 100
    step: 2
    icon: mdi:volume-high

  loop_delay:
    name: "Atrasar ciclo"
    initial: 1
    min: 0
    max: 15
    step: 1
    icon: mdi:loop

input_select:
  gateway_sound:
    name: Toque
    options:
      - "0 - Police car 1"
      - "1 - Police car 2"
      - "2 - Accident"
      - "3 - Countdown"
      - "4 - Ghost"
      - "5 - Sniper rifle"
      - "6 - Battle"
      - "7 - Air raid"
      - "8 - Bark"
      - "10 - Doorbell"
      - "11 - Knock at a door"
      - "12 - Amuse"
      - "13 - Alarm clock"
      - "20 - MiMix"
      - "21 - Enthusiastic"
      - "22 - GuitarClassic"
      - "23 - IceWorldPiano"
      - "24 - LeisureTime"
      - "25 - ChildHood"
      - "26 - MorningStreamLiet"
      - "27 - MusicBox"
      - "28 - Orange"
      - "29 - Thinker"
#      - "10001 - Bum Bum Tam Tam"
#      - "10002 - Beep Beep"
#      - "10003 - Time beep 3x"
#      - "10004 - Mi gente"
#      - "10005 - Time beep 4x"
#      - "10006 - Car lock"
    icon: mdi:music-note
