#--------------------------------------------------------------------
#	Home Assistant - Geo Location
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-20
#	Description :	Set configuration to Geo Location
#--------------------------------------------------------------------

homeassistant:
  customize:
    sensor.flavio_location:
      friendly_name: Localização de Flávio
      icon: mdi:crosshairs-gps
    camera.flavio_map:
      friendly_name: Localização de Flávio

group:
  Location:
    name: Localização
    entities:
      - sensor.flavio_location
      - camera.flavio_map

sensor:
  - platform: google_geocode
    name: Flavio Location
    api_key: !secret google_travel_api
    origin: device_tracker.flavio_tracker
    options: formatted_address
#    display_zone: hide

camera:
  - platform: generic
    name: Flavio Map
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?size=800x800&maptype=satellite&markers=color:gray|label:F|{{ states.device_tracker.flavio_tracker.attributes.latitude }},{{ states.device_tracker.flavio_tracker.attributes.longitude }}&markers=color:green|label:H|{{ states.device_tracker.flavio_tracker.attributes.latitude }},{{ states.device_tracker.flavio_tracker.attributes.longitude }}
    limit_refetch_to_url_change: true
