#--------------------------------------------------------------------
#	Home Assistant - Owntracks
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-20
#	Description :	Set configuration to Owntracks
#--------------------------------------------------------------------

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

  - platform: mqtt_json
    devices:
      flavio_tracker: zanzito/flavio_tracker/location

sensor:
  - platform: mqtt
    name: Estado da bateria
    state_topic: "zanzito/flavio_tracker/device_info"
    value_template: >-
      {% if value_json.battery_charging == true %}
        A carregar
      {% else %}
        A descarregar
      {% endif %}

  - platform: template
    sensors:
      flavio_battery:
        friendly_name: Bateria de Flávio
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.device_tracker.flavio_tracker.attributes.battery %}
            {{ states.device_tracker.flavio_tracker.attributes.battery|round }}
          {% else %}
            {{ states.sensor.flavio_battery.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.flavio_battery.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      flavio_charging:
        friendly_name: Estado da bateria de Flávio
        value_template: '{{ states.sensor.estado_da_bateria.state }}'
        icon_template: >-
          {% if states.sensor.estado_da_bateria.state == "A carregar" %}
            mdi:battery-charging
          {% else %}
            mdi:mdi:battery-minus
          {%- endif %}

      flavio_phone:
        value_template: '{% if is_state("device_tracker.flavio_phone", "home") %} Casa {% else %} Ausente {%- endif %}'

group:
  Family:
    name: Família
    entities:
      - sensor.flavio_phone
      - sensor.flavio_battery
      - sensor.flavio_charging
