#--------------------------------------------------------------------
#	Home Assistant - System Monitor
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-17
#	Description :	Set configuration to System Monitor
#--------------------------------------------------------------------

homeassistant:
  customize:
    script.restart_ha:
      icon: mdi:autorenew
    script.reboot_pi:
      icon: mdi:power
    sensor.cpu_use:
      friendly_name: 'Uso CPU'
    sensor.ram_free:
      friendly_name: 'RAM livre'
      icon: mdi:chip
    sensor.disk_free_:
      friendly_name: 'Espaço livre'
      unit_of_measurement: 'Gb'
    sensor.last_boot:
      friendly_name: 'Último reinício'
    sensor.hassbian_last_boot:
      friendly_name: 'Uptime HA'
      unit_of_measurement: 'horas'
    sensor.since_last_boot_templated:
      friendly_name: 'Uptime Pi'
      icon: mdi:clock
    sensor.connected_clients:
      friendly_name: 'Clientes conectados'
      unit_of_measurement: 'cliente(s)'
      icon: 'mdi:account'

group:
  Estado HA:
    name: Sistema HA
    control: hidden
    entities:
      - script.restart_ha
      - script.reboot_pi
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.disk_free_
      - sensor.last_boot
      - sensor.hassbian_last_boot
      - sensor.since_last_boot_templated
      - sensor.connected_clients

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: since_last_boot

  - platform: uptime
    name: Hassbian Last Boot
    unit_of_measurement: hours

  - platform: api_streams

  - platform: template
    sensors:
      since_last_boot_templated:
        value_template: >-
          {%- if states.sensor.since_last_boot -%}
            {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
            {%- set count = slb | length -%}
            {%- set hms = slb[count - 1] -%}
            {%- set hms_split = hms.split(':') -%}
            {%- set hours = hms_split[0] | int -%}
            {%- set minutes = hms_split[1] | int -%}
            {%- if count == 3 -%}
              {%- set days = slb[0] | int -%}
            {%- else -%}
              {%- set days = 0 -%}
            {%- endif -%}
            {%- if days == 0 and hours == 0 and minutes == 0 -%}
              Menos de 1 min
            {%- else -%}
              {%- if days > 0 -%}
                {%- if days == 1 -%}
                  1 dia
                {%- else -%}
                  {{ days }} dias
                {%- endif -%}
              {%- endif -%}
              {%- if hours > 0 -%}
                {%- if days > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if hours == 1 -%}
                  1 hora
                {%- else -%}
                  {{ hours }} horas
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if days > 0 or hours > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 min
                {%- else -%}
                  {{ minutes }} min
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- else -%}
            n/a
          {%- endif -%}

script:
  restart_ha:
    alias: 'Reiniciar HA'
    sequence:
      - service: homeassistant.restart

  reboot_pi:
    alias: 'Reiniciar Pi'
    sequence:
      - service: shell_command.reboot_pi

shell_command:
  reboot_pi: sudo reboot
