#--------------------------------------------------------------------
#	Home Assistant - Transmission
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-01-17
#	Description :	Set configuration to Transmission
#--------------------------------------------------------------------

homeassistant:
  customize:
    sensor.transmission_estado:
      icon: mdi:download
    sensor.transmission_down_speed:
      friendly_name: Download
      icon: mdi:cloud-download
    sensor.transmission_up_speed:
      friendly_name: Upload
      icon: mdi:cloud-upload
    sensor.transmission_active_torrents:
      friendly_name: Torrents ativos
      icon: mdi:arrow-right-bold-circle-outline
    switch.transmission_turtle_mode:
      friendly_name: Limitar velocidade
      icon: mdi:trending-down
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true

group:
  Transmission:
    name: Transmission
    entities:
      - sensor.transmission_estado
      - sensor.transmission_down_speed
      - sensor.transmission_up_speed
      - sensor.transmission_active_torrents
      - switch.transmission_turtle_mode

sensor:
  - platform: transmission
    host: !secret transmission_host
    port: !secret transmission_port
    username: !secret transmission_username
    password: !secret transmission_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
      - 'active_torrents'

  - platform: template
    sensors:
      transmission_estado:
        friendly_name: 'Estado'
        value_template: >
          {%- if is_state('sensor.transmission_status', 'idle') -%}
            Inativo
          {%- elif is_state('sensor.transmission_status', 'Downloading') -%}
            A receber
          {%- elif is_state('sensor.transmission_status', 'Seeding') -%}
            A enviar
          {%- elif is_state('sensor.transmission_status', 'Up/Down') -%}
            Enviar/Receber
          {%- endif -%}

switch:
  - platform: transmission
    host: !secret transmission_host
    port: !secret transmission_port
    username: !secret transmission_username
    password: !secret transmission_password
