#--------------------------------------------------------------------
#	Home Assistant - Travels
#--------------------------------------------------------------------
#	Author		:	Flávio Pinho
#	Date		:	2018-02-08
#	Description :	Set configuration to Travels
#--------------------------------------------------------------------

homeassistant:
  customize:
    sensor.home2work:
      friendly_name: Casa -> Trabalho
      icon: mdi:car-sports
    sensor.work2desafio:
      friendly_name: Trabalho -> Desafio Fit
      icon: mdi:car-sports
    sensor.work2ffitness:
      friendly_name: Trabalho -> FFitness
      icon: mdi:car-sports
    sensor.desafio2home:
      friendly_name: Desafio Fit -> Casa
      icon: mdi:car-sports
    sensor.ffitness2home:
      friendly_name: FFitness -> Casa
      icon: mdi:car-sports
    sensor.home2home_couto:
      friendly_name: Casa -> Casa da Mãe
      icon: mdi:car-sports

group:
  Travels:
    name: Viagens
    entities:
      - sensor.home2work
      - sensor.work2desafio
      - sensor.work2ffitness
      - sensor.desafio2home
      - sensor.ffitness2home
      - sensor.home2home_couto

sensor:
  - platform: google_travel_time
    name: Home2Work
    api_key: !secret google_travel_api
    origin: zone.casa
    destination: zone.trabalho
#    origin: place_id:ChIJ99dZOmk2Iw0RFt7_Mx_j7eo
#    destination: place_id:ChIJ3_tpnaI2Iw0R8Gp-25NozpA
    options:
      mode: driving

  - platform: google_travel_time
    name: Work2Desafio
    api_key: !secret google_travel_api
    origin: zone.trabalho
    destination: zone.desafio_fit
#    origin: place_id:ChIJ3_tpnaI2Iw0R8Gp-25NozpA
#    destination: place_id:ChIJ3emtJA43Iw0R_0xZR1pMiu8
    options:
      mode: driving

  - platform: google_travel_time
    name: Work2Ffitness
    api_key: !secret google_travel_api
    origin: zone.trabalho
    destination: zone.ffitness
#    origin: place_id:ChIJ3_tpnaI2Iw0R8Gp-25NozpA
#    destination: place_id:ChIJt-C3ILo3Iw0RO-c6GcYxuBY
    options:
      mode: driving

  - platform: google_travel_time
    name: Desafio2Home
    api_key: !secret google_travel_api
    origin: zone.desafio_fit
    destination: zone.casa
#    origin: place_id:ChIJ3emtJA43Iw0R_0xZR1pMiu8
#    destination: place_id:ChIJ99dZOmk2Iw0RFt7_Mx_j7eo
    options:
      mode: driving

  - platform: google_travel_time
    name: Ffitness2Home
    api_key: !secret google_travel_api
    origin: zone.ffitness
    destination: zone.casa
#    origin: place_id:ChIJt-C3ILo3Iw0RO-c6GcYxuBY
#    destination: place_id:ChIJ99dZOmk2Iw0RFt7_Mx_j7eo
    options:
      mode: driving

  - platform: google_travel_time
    name: Home2Home_Couto
    api_key: !secret google_travel_api
    origin: zone.casa
    destination: zone.casa_couto
#    origin: place_id:ChIJ99dZOmk2Iw0RFt7_Mx_j7eo
#    destination: place_id:ChIJ4ZEvZROCIw0RLrEVzvNOi50
    options:
      mode: driving
